2024-04-03 23:02:24,780 ERROR: Exception on /user/Real [GET] [in C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\app\routes.py", line 102, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'InstrumentedList' object has no attribute 'order_by'
2024-04-03 23:03:55,067 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:48]
2024-04-04 03:04:07,182 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:48]
2024-04-04 16:17:31,780 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 16:18:35,879 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 16:40:31,577 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 16:41:21,199 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 16:48:57,388 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 16:55:54,325 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:02:05,760 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:03:50,872 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:05:53,859 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:12:42,254 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:19:06,764 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:23:31,117 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:27:13,084 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:33:05,159 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-04 17:33:45,567 ERROR: Exception on /index [GET] [in C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py:828]
Traceback (most recent call last):
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\app\routes.py", line 36, in index
    return render_template("index.html", title='Home Page', form=form,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\JERRY\Favorites\microblog\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\JERRY\Favorites\microblog\app\templates\index.html", line 29, in template
    {% block content %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2024-04-04 17:38:43,857 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:50]
2024-04-05 12:02:28,074 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-05 12:06:05,781 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-05 12:15:19,038 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-05 12:16:15,236 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-06 00:22:44,785 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-06 00:23:55,229 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-06 00:23:55,329 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-06 00:23:55,329 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
2024-04-06 00:26:37,256 INFO: Microblog startup [in C:\Users\JERRY\Favorites\microblog\app\__init__.py:52]
